# config.yaml
camera_config:
  intrinsic_path: nudge_test/motor/camera_intrinsics.npz
  extrinsic_path: nudge_test/motor/camera_extrinsics.npz
nudge_plane_geometry: # nudge plane = ceiling
  normal_vector: [0.0, 0.0, 1.0]  # nudge 평면 법선 벡터
  nudge_plane_displacement: 2500
nudge_screen_geometry:
  screen_width: 354.0    # nudge 스크린 폭 mm
  screen_ratio: 16/9   # nudge 스크린 가로세로 비율
pan_tilt_height: 1350  # 빔프로젝터 회전축 높이 mm
projector_offset_vector: [50.0, 0.0, 150.0]  # 빔프로젝터 광선과 tilt 회전축 간 오프셋 벡터 mm
qa_config:
  qa_plane_normal_vec: [0.0, 0.0, 1.0]  # 천장 법선 벡터
  qa_plane_displacement: 400.0    # 천장과 빔프로젝터 광선 교차점 거리 mm
  qa_screen_width: 354.0    # 스크린 폭 mm
  qa_screen_ratio: 16/9
  qa_pan: 63
  qa_tilt: 111
serial:
  port: COM5
  baudrate: 115200
  timeout: 1.0
motor:
  pan:
    min_deg: 0
    max_deg: 180
    init_deg: 63
  tilt:
    min_deg: 50
    max_deg: 170
    init_deg: 111